name: Build Terraform Compliance Docker Image

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false  

jobs:
  terraform:
    name: 'Docker'
    runs-on: evinvesttechnonprod-us-east-1-dev-selfhosted-runner

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout (Latest)
      uses: Eaton-Vance-Corp/checkout@v2
      if: github.event.inputs.git-ref == ''
    - name: Checkout (Provided Ref)
      uses: Eaton-Vance-Corp/checkout@v2
      if: github.event.inputs.git-ref != ''
      with:
        ref: ${{ github.event.inputs.git-ref }}
    
    - name: Configure Docker Registry
      run: docker login $REGISTRY -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
      env:
        REGISTRY: docker.pkg.github.com
        
    - name: Build Docker Image
      run: |
       docker build . -t $REGISTRY/$GITHUB_REPOSITORY/terraform-compliance:latest
       docker push $REGISTRY/$GITHUB_REPOSITORY/terraform-compliance:latest
      
